[#35] 쿠폰 받기
f-lab-edu/online-marketplace pull request #42
Opened 2021-08-17 05:57 UTC by sileeee

# 변경 사항
- 로그인 검증 로직
  - 사용자 아이디를 PathVariable로 받지 않는 상황을 고려하여 수정        
- 쿠폰 받기 로직
  - 만료시간이 지나지 않고, 이미 받은 쿠폰이 아닐 경우에만 저장 가능

2021-08-18 04:11 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	private final HttpSession httpSession;
쿠폰서비스에서 직접 `HttpSession`을 사용하는 것보다는 우리가 세션을 사용하려는 용도에 맞는 클래스로 캡슐화하여 사용하는게 나아보입니다~

2021-08-19 08:17 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	private final HttpSession httpSession;
넵 수정했습니다! 확인 부탁드려요😃

2021-08-19 16:01 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Optional<Coupon> findAvailableCouponId(long id);
`findAvaliableCouponById` 가 되어야 할 것 같아요! 사용 가능한 쿠폰의 ID 를 준다는 의미로 메소드가 잘못 읽힐 가능성이 있는 것 같네요!

2021-08-19 16:01 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Optional<UserCoupon> findByCouponId(long id);
1. 이건 그냥 선호이지만, `findUserCouponById` 라고 쓰는 게 간결한 것 같은데 시은님 생각은 어떠신가요? 😀
2. 저희 repository 메소드를 컨벤션 맞추면 어떨까요? `find`다음에 엔티티명을 붙여주는 게 좋을 것 같습니다! `findCoupons`, `findCouponById` 처럼요

2021-08-19 16:01 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/global/util/session/HttpSessionUtil.java
> +		return httpSession.getAttribute(SessionKey.LOGIN_USER_ID);
세션키를 고정하는 것보다 `util`을 사용하는 객체가 선택하는 편이 확장성이 높지 않을까요?

2021-08-19 16:01 UTC, hello-jiwon commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        WHERE id = #{id} AND expiration_time &gt; NOW()
사용 가능한 쿠폰인지 확인하는 로직이 직관적이지 않은 것 같아요!
"쿠폰이 사용 가능한지 확인" 하는 것의 책임은 service 계층의 책임이라고 생각하는데, repository 계층에 위임된 것 같다는 생각이 드네요!
repository 는 ID 로 쿠폰을 가져오고, service 계층은 쿠폰의 `expiration_time` 을 검사하는 것은 어떨까요? 😀

2021-08-19 16:01 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		couponRepository.insertUserCoupon(userCoupon);
멀티스레드 환경에서, 한 명의 사용자가 여러 개의 쿠폰을 받을 위험이 생기지 않을까요?

2021-08-23 02:54 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	private final HttpSessionUtil httpSessionUtil;
1. 세션을 사용한다라기보다는 현재 인증된 유저의 정보를 가져오는 것이므로 인증의 책임을 가진 클래스를 만들어 그 곳에 의존시키는게 어떨까요?
2. 여러 PR에서 중복 커밋을 날리면 conflict가 발생할 수 있습니다. 확인을 한번 해보시면 좋을 것 같아요

2021-08-24 03:45 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Optional<Coupon> findAvailableCouponId(long id);
아 그렇네요~ 수정하겠습니다! 감사합니다!

2021-08-24 03:48 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Optional<UserCoupon> findByCouponId(long id);
1. 무엇을 찾는 것인지 명확하게 나타나지 않은 메소드명이었네요! 수정하겠습니다!
2. 네 좋은 것 같습니다~ 이번 이슈에서 메소드명에 고민이 있었는데 컨벤션을 맞추면 훨씬 수월할 것 같아요😄

2021-08-24 06:44 UTC, sileeee commented on src/main/java/com/coupang/marketplace/global/util/session/HttpSessionUtil.java
> +		return httpSession.getAttribute(SessionKey.LOGIN_USER_ID);
제가 다시 생각해보니 인증(로그인)의 책임 분리를 위해 만들어 둔 `LoginService`인터페이스를 사용하면 되겠더라구요! 메소드명을 `getLoginUserId`로 하여 메소드를 추가하였는데 확인 부탁드립니다😃

2021-08-24 07:14 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	private final HttpSessionUtil httpSessionUtil;
1. 인증의 책임을 가진 인터페이스인 `UserService`를 구현한 클래스에서 사용자의 아이디를 가져올 수 있도록 수정하였습니다! 
2. 앗 넵 알겠습니다~

2021-08-27 15:31 UTC, sileeee commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        WHERE id = #{id} AND expiration_time &gt; NOW()
각 계층의 책임이 분리될 수 있어 좋은 것 같습니다! 꼼꼼하게 확인해주셔서 감사합니다😃

2021-08-27 15:32 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		couponRepository.insertUserCoupon(userCoupon);
넵 그런 상황을 생각해보아야겠군요~~ 수정하겠습니다!😄

2021-09-02 13:32 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/controller/CouponController.java
> +	@Qualifier("userSessionLoginService")
생성자 주입이라면 생성자에 `@Qualifier`를 붙여주어야합니다~ lombok을 이용하고 계시다면 생성자를 직접 만드셔야할 것 같네요

2021-09-09 04:04 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/global/config/WebConfig.java
> +{
이거는 컨벤션을 바꾸신 이유가 있으실까요?

2021-09-10 06:57 UTC, sileeee commented on src/main/java/com/coupang/marketplace/global/config/WebConfig.java
> +{
앗 실수로 그렇게 되었습니다! 수정하겠습니다

2021-09-10 07:18 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/controller/CouponController.java
> +	@Qualifier("userSessionLoginService")
혹시 다시 설명해주실 수 있으실까요? 저는 어노테이션 `@RequiredArgsConstructor`을 통해 생성자를 만들고 그 때, `@Qualifier`로 파라미터를 `userSessionLoginService`로 특정할 수 있다고 생각하였습니다! 그래서 왜 생성자를 직접 만들어야 하는지 이해를 하지 못했습니다..😭

2021-09-10 09:14 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Long insertUserCoupon(UserCoupon userCoupon);
여기서는 null이 리턴될 가능성이 있어서 Reference type으로 쓰신걸까요?

2021-09-10 09:14 UTC, f-lab-dev commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        <selectKey keyProperty="coupon_id" resultType="java.lang.Long" order="AFTER">
이렇게 하면 쿼리는 `insert`와 `select` 2개가 나가는데 이 쿼리가 동시에 엄청 많이 실행하면 동시성 문제가 생길 것 같은데 어떻게 정확한 정보를 리턴할 수 있는걸까요?

2021-09-14 03:00 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/repository/CouponRepository.java
> +	Long insertUserCoupon(UserCoupon userCoupon);
`Mybatis`에서는 기본적으로 쿼리가 돌고 나면 업데이트 한 행의 개수를 리턴하여 null이 반환될 가능성은 없을 것 같습니다. 저는 `null이 리턴되어 예외로 처리 할 가능성이 있으면 Reference type을 사용하지 않아도 된다`고 이해를 했었는데 혹시 맞을까요..?

2021-09-14 03:00 UTC, sileeee commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        <selectKey keyProperty="coupon_id" resultType="java.lang.Long" order="AFTER">
`selectKey`를 사용하면 `select`로 사용하는 방식보다 멀티스레드 상황에서 안전하게 값을 가져올 수 있습니다. 방금 입력된 값의 컬럼값인 `auto_increment` 데이터를 바로 가져오기 때문입니다.

2021-10-07 05:56 UTC, f-lab-dev commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        <selectKey keyProperty="coupon_id" resultType="java.lang.Long" order="AFTER">
락과 관련된 답변을 해주시면 좋을 것 같아요~

2021-10-20 10:30 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	@Transactional(rollbackFor = RuntimeException.class)
`rollbackFor` 설정은 어떤 이유로 하신 걸까요?
`@Transactional`은 기본적으로 RuntimeException, Error에 대한 롤백을 하고 있어서 명시해줄 필요가 없을 것 같아서요!

2021-10-20 10:30 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/global/config/WebConfig.java
> +public class WebConfig extends WebMvcConfigurationSupport{
`WebMvcConfigurer`을 `WebMvcConfigurationSupport`로 대체한 이유가 있을까요? 😀

2021-10-21 14:23 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +	@Transactional(rollbackFor = RuntimeException.class)
아 그렇군요! 수정하겠습니다 감사합니다~

2021-10-21 15:49 UTC, sileeee commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +        <selectKey keyProperty="coupon_id" resultType="java.lang.Long" order="AFTER">
생성된 `auto_increment` 데이터는 접속별로 서버에서 유지 관리됩니다. 그래서 다른 스레드의 영향을 받을 수 없어 락이나 트랜잭션이 없이도 안전하게 값을 가져올 수 있습니다.

2021-10-23 11:57 UTC, sileeee commented on src/main/java/com/coupang/marketplace/global/config/WebConfig.java
> +public class WebConfig extends WebMvcConfigurationSupport{
로그인 검증 로직을 수정하면서 발생한 오류를 해결하다가 상관없는 부분을 건드린 것 같습니다..!😅 확인해주셔서 감사합니다.
일단 차이점으로 `WebMvcConfigurationSupport`은 `WebMvcConfigurer`와 다르게 Spring Boot가 제공하는 Convention을 따르지 않고 설정가능합니다. 그래서 개발자 제어가 가능하게 됩니다.

2021-10-29 12:41 UTC, f-lab-dev requested changes

2021-10-29 12:41 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
>  			throw new RuntimeException("쿠폰 저장 오류");
어떤 값을 넣었더니 오류가 난건지 `userCoupon`을 로그에 찍어주면 나중에 에러가 발생했을 때 원인을 파악하는데에 좋을 것 같아요~

2021-10-29 12:41 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(insertCouponId != 1){
1로 해주신 이유가 있으신가요? 입력된 id는 매번 바뀔 것 같은데요~

2021-10-30 07:57 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(insertCouponId != 1){
`selectKey`에서 `keyProperty`로 설정한 `id`값을 찍어봤더니 항상 `1`이 나왔습니다. 그래서 확인을 해보았더니 원래 컬럼값에서 `auto_increment`로 +1이 된 값이 반환되는 것이 아니라 추가된 row값을 반환되었습니다. 한 명의 사용자가 하나의 쿠폰을 받는 것을 보장하기 위해서는 1이어야 한다고 판단하였기 때문에 `1`로 고정하였습니다!

2021-10-30 08:09 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
>  			throw new RuntimeException("쿠폰 저장 오류");
아 그렇네요~ `userCoupon`과 추가된 쿠폰의 수를 `insertCouponCount`로 하여 로그에 찍히도록 수정하였습니다!

2021-10-31 12:52 UTC, hello-jiwon approved these changes

2021-10-31 23:27 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(insertCouponId != 1){
그럼 `insertUserCoupon` 메소드가 의도한대로 처리되지 않은 것 같은데 의도하셨던거는 마지막 ID를 가져오고 싶으셨던 것 아니였을까요??

2021-10-31 23:28 UTC, f-lab-dev commented
코멘트 드린 부분만 한번 확인 부탁드려요~

2021-11-01 07:54 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(insertCouponId != 1){
그렇군요! 따로 말씀주신대로 비즈니스 요구사항에따라 달라질 수 있는 부분이어서 수정해야겠군요😃 코멘트 달아주셔서 감사합니다~

2021-11-03 11:42 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(maxCouponCount.equals(Integer.valueOf(issuedCouponCount)))
이거는 굳이 equals를 써서 비교해야할까요?

2021-11-03 11:42 UTC, f-lab-dev commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +    <select id="getMaxCouponCount" resultType="java.lang.Integer">
max_count가 null이라면 어떤 것을 의미하는걸까요?

2021-11-04 16:00 UTC, sileeee commented on src/main/resources/mybatis/mapper/CouponMapper.xml
> +    <select id="getMaxCouponCount" resultType="java.lang.Integer">
쿠폰의 사용을 중지하기를 원하는 등, max_count가 null인 상황이 발생할 수 있어 참조자료형을 사용하였습니다. 하지만 로직상 임의로 max_count의 값을 null로 만드는 행위는 위험한 것입니다. 결과적으로 null값을 가질 상황이 없을 것이므로 primitive형으로 수정해야할 것 같습니다!

2021-11-04 16:02 UTC, sileeee commented on src/main/java/com/coupang/marketplace/coupon/service/CouponService.java
> +		if(maxCouponCount.equals(Integer.valueOf(issuedCouponCount)))
max_count를 참조자료형으로 정의하여 equals메소드를 사용해 비교를 하였는데, 자료형을 primitive형으로 바꿀 계획이므로 이 부분도 같이 수정하겠습니다!

2021-11-07 12:31 UTC, f-lab-dev approved these changes

2021-11-08 12:12 UTC, merged