Feature/3
f-lab-edu/online-marketplace pull request #7
Opened 2021-06-27 12:49 UTC by sileeee

# 변경 사항

- 로그인 기능 구현
- 로그인 세션 추가

2021-06-27 14:55 UTC, hello-jiwon requested changes

2021-06-27 14:55 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +        }
`else` 문에 굳이 넣을 필요없는 것 같습니다!

2021-06-27 14:55 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +
불필요한 개행인 것 같습니다!

2021-06-27 14:55 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +            }
```suggestion
            if(!encryptedPassword.equals(user.get().getPassword())){
            	throw new IllegalArgumentException("패스워드가 틀렸습니다.");
            }
            httpSession.setAttribute(SessionKey.LOGIN_USER_ID, user.get().getId());
```
이렇게 쓴다면 더 간결해지지 않을까요? 😀 제안입니다!

2021-06-27 14:55 UTC, hello-jiwon commented on src/main/java/com/coupang/marketplace/util/SessionKey.java
> +}
`util`은 비즈니스 로직과는 독립적으로 반복 사용될 가능성이 있는 "유틸리티성 기능"들을 모아두는 패키지입니다 보안과 관련된 암호화 기능 처럼요!
SessionKey 정보는 util 패키지에 적합하지 않은 것 같습니다!

2021-06-27 17:14 UTC, sileeee commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +            }
아 그렇겠네요! 수정하도록 하겠습니다😊

2021-06-27 17:15 UTC, sileeee commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +
넵 수정하겠습니다!

2021-06-27 17:51 UTC, sileeee commented on src/main/java/com/coupang/marketplace/util/SessionKey.java
> +}
세션의 키는 많은 Controller에서 사용될 수 있기 때문에, 따로 분리하여 상수로 관리하려는 목적으로 util패키지에 SessionKey클래스를 만들었습니다!
해당 상수를 Service에서 정의하는 것이 좋을까요??

2021-06-28 04:01 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +    private final HttpSession httpSession;
생성자 주입으로 세션을 잘 받으셨군요 👍

2021-06-28 04:01 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +    public void login(SignInRequestDto dto){
로그인은 `인증한다`라는 행위입니다. `UserService`가 갖고있는 책임에 속하는지, 확장가능성은 어떤지 한번 고려해보시면 좋겠네요~

2021-06-28 04:01 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/util/SessionKey.java
> +}
지원님의 의도는 상수용 패키지를 만드는 등 유틸 패키지가 아닌 다른 곳에 이 클래스를 위치시켜달라는 말인 것 같네요~

2021-06-28 14:09 UTC, sileeee commented on src/main/java/com/coupang/marketplace/util/SessionKey.java
> +}
넵! 상수용 패키지를 만들었습니다! 감사합니다😊

2021-06-28 14:12 UTC, sileeee commented on src/main/java/com/coupang/marketplace/service/UserService.java
> +    public void login(SignInRequestDto dto){
```LoginService```로 책임을 분리해보았고, 확장에 용이하도록 인터페이스를 만들었습니다!

2021-06-29 09:04 UTC, f-lab-dev commented on src/main/java/com/coupang/marketplace/service/SessionLoginService.java
> +        else {
1. else문은 굳이 필요 없어보이네요~
2. else문의 위치에 대해 코딩 컨벤션을 정해보면 좋을 것 같은데 checkstyle에 대해 알아보시면 좋을 것 같아요~

2021-07-05 16:35 UTC, sileeee commented on src/main/java/com/coupang/marketplace/service/SessionLoginService.java
> +        else {
1. 넵 수정하겠습니다!
2. code convention으로 지정한 것을 따라 checkstyle을 적용하였습니다!

2021-07-06 07:07 UTC, f-lab-dev approved these changes
이 checkstyle 적용한 내용은 지원님과도 함께 공유되면 좋을 것 같습니다~

2021-07-06 10:17 UTC, hello-jiwon approved these changes

2021-07-08 08:22 UTC, merged